In [21]:
import pandas as pd

In [22]:
df = pd.read_csv('Animal_Shelter_Animals_20250221.csv')

In [23]:
df.head()

,id,intakedate,intakereason,istransfer,sheltercode,identichipnumber,animalname,breedname,basecolour,speciesname,...,movementdate,movementtype,istrial,returndate,returnedreason,deceaseddate,deceasedreason,diedoffshelter,puttosleep,isdoa
0,15801,11/28/2009 12:00:00 AM,Moving,False,C09115463,0A115D7358,Jadzia,Domestic Short Hair,Tortoiseshell,Cat,...,05/13/2017 12:00:00 AM,Adoption,False,10/31/2024 12:00:00 AM,Owner requested Euthanasia,10/31/2024 12:00:00 AM,Owner Requested,False,True,False
1,15932,12/08/2009 12:00:00 AM,Moving,False,D09125594,0A11675477,Gonzo,German Shepherd Dog/Mix,Tan,Dog,...,04/24/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
2,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,04/15/2017 12:00:00 AM,Adoption,False,02/28/2020 12:00:00 AM,Stray,06/28/2024 12:00:00 AM,Court Order/ Legal,True,False,False
3,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,02/29/2020 12:00:00 AM,Reclaimed,False,11/06/2023 12:00:00 AM,Stray,06/28/2024 12:00:00 AM,Court Order/ Legal,True,False,False
4,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,12/17/2023 12:00:00 AM,Adoption,False,NaN,Stray,06/28/2024 12:00:00 AM,Court Order/ Legal,True,False,False

In [24]:
df = df.drop_duplicates(subset='id', keep='last')
df.head()

,id,intakedate,intakereason,istransfer,sheltercode,identichipnumber,animalname,breedname,basecolour,speciesname,...,movementdate,movementtype,istrial,returndate,returnedreason,deceaseddate,deceasedreason,diedoffshelter,puttosleep,isdoa
0,15801,11/28/2009 12:00:00 AM,Moving,False,C09115463,0A115D7358,Jadzia,Domestic Short Hair,Tortoiseshell,Cat,...,05/13/2017 12:00:00 AM,Adoption,False,10/31/2024 12:00:00 AM,Owner requested Euthanasia,10/31/2024 12:00:00 AM,Owner Requested,False,True,False
1,15932,12/08/2009 12:00:00 AM,Moving,False,D09125594,0A11675477,Gonzo,German Shepherd Dog/Mix,Tan,Dog,...,04/24/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
6,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,NaN,NaN,False,NaN,Stray,06/28/2024 12:00:00 AM,Court Order/ Legal,True,False,False
8,30812,01/11/2013 12:00:00 AM,Abandoned,False,C1301091,0A13403D4D,Pretty Girl,Domestic Short Hair,Dilute tortoiseshell,Cat,...,05/29/2018 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
10,31469,03/26/2013 12:00:00 AM,Incompatible with owner lifestyle,False,D1303720,981020007006095,Bonnie,Basenji/Mix,Brown and White,Dog,...,05/09/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False

In [25]:
df = df[df['deceaseddate'].isna()].reset_index(drop=True)
df.head()

,id,intakedate,intakereason,istransfer,sheltercode,identichipnumber,animalname,breedname,basecolour,speciesname,...,movementdate,movementtype,istrial,returndate,returnedreason,deceaseddate,deceasedreason,diedoffshelter,puttosleep,isdoa
0,15932,12/08/2009 12:00:00 AM,Moving,False,D09125594,0A11675477,Gonzo,German Shepherd Dog/Mix,Tan,Dog,...,04/24/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
1,30812,01/11/2013 12:00:00 AM,Abandoned,False,C1301091,0A13403D4D,Pretty Girl,Domestic Short Hair,Dilute tortoiseshell,Cat,...,05/29/2018 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
2,31469,03/26/2013 12:00:00 AM,Incompatible with owner lifestyle,False,D1303720,981020007006095,Bonnie,Basenji/Mix,Brown and White,Dog,...,05/09/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
3,40705,06/19/2015 12:00:00 AM,Abandoned,False,R15061738,NaN,Candy,American Sable/American,Brown,House Rabbit,...,04/12/2017 12:00:00 AM,Transfer,False,NaN,Stray,NaN,Died in care,False,False,False
4,40706,06/19/2015 12:00:00 AM,Abandoned,False,R15061739,NaN,Charlotte,American Sable/American,Brown,House Rabbit,...,04/12/2017 12:00:00 AM,Transfer,False,NaN,Stray,NaN,Died in care,False,False,False

In [27]:
df.to_csv('filtered_pet_data.csv', index=False)

In [28]:
dups = df[df.duplicated(subset=['id'], keep=False)]
dups

Empty DataFrame
Columns: [id, intakedate, intakereason, istransfer, sheltercode, identichipnumber, animalname, breedname, basecolour, speciesname, animalage, sexname, location, movementdate, movementtype, istrial, returndate, returnedreason, deceaseddate, deceasedreason, diedoffshelter, puttosleep, isdoa]
Index: []

[0 rows x 23 columns]